version: '2.1'
services:
    dbuntu:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dbuntu
        network_mode: "host"
        volumes:
            - ./export/home1/username/cscope_db/:/export/home1/username/cscope_db/
            - ~/.m2/:/root/.m2/
            - ~/loadrc/:/root/loadrc/
        command: /bin/sh -c "/entrypoint.sh > /var/log/containner.log 2>&1"
