version: '2.0'
services:
    dbuntu:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dbuntu
        volumes:
            - ~/.m2/:/root/.m2/
            - ~/loadrc/:/root/loadrc/
            - ~/loadrc/gitrc/.gitconfig:/root/.gitconfig
            - ./.bashrc:/root/.bashrc
            - ./var/logs/:/var/logs/
            - ./etc/apt/sources.list:/etc/apt/sources.list
        command: /bin/sh -c "/entrypoint.sh > /var/logs/containner.log 2>&1"
