version: '3.0'
services:
    dbuntu:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dbuntu
        volumes:
            - ./export/home1/username/cscope_db/:/export/home1/username/cscope_db/
            - ~/.m2/:/root/.m2/
            - ~/loadrc/:/root/loadrc/
            - ~/loadrc/gitrc/.gitconfig:/root/.gitconfig
            - ./.bashrc:/root/.bashrc
            - ./var/logs/:/var/logs/
        command: /bin/sh -c "/entrypoint.sh > /var/logs/containner.log 2>&1"
