version: '2'
services:
    dbuntu:
        build:
            context: .
            dockerfile: Dockerfile
        image: huangyingw/dbuntu
        network_mode: "host"
        volumes:
            - ./var/log/:/var/log/
        command: /bin/sh -c "/entrypoint.sh > /var/log/containner.log 2>&1"
